import hashlib
import secrets
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode
from urllib.request import Request, build_opener, HTTPRedirectHandler
import os
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from database import get_db_connection

from datetime import date, datetime
from pydantic import BaseModel
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors

app = FastAPI()

# Receipt files are generated by the ClassAI backend so the existing parent
# website can open them without any website-side code changes.
RECEIPT_DIR = Path(__file__).resolve().parent / "receipts"
RECEIPT_DIR.mkdir(parents=True, exist_ok=True)
BACKEND_BASE_URL = "https://classai-backend-a69s.onrender.com"


class PaymentRequest(BaseModel):
    due_id: int
    payment_mode: str
    transaction_no: Optional[str] = None
    remarks: Optional[str] = None


class EmployeeCreate(BaseModel):
    schoolId: int
    fullName: str
    mobile: str
    userId: str
    password: str


class AdminCreate(BaseModel):
    fullName: str
    mobile: str
    userId: str
    password: str


class AdminStatusUpdate(BaseModel):
    isActive: int


class EmployeeUpdate(BaseModel):
    schoolId: int
    fullName: str
    mobile: str
    userId: str
    password: Optional[str] = None


class LoginRequest(BaseModel):
    userId: str
    password: str
    role: str


@app.post("/payments")
def make_payment(payment: PaymentRequest):

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    cursor.execute("""
        SELECT
            id,
            student_id,
            amount,
            COALESCE(penalty, 0) AS penalty,
            COALESCE(waiver, 0) AS waiver,
            net_amount,
            transaction_no
        FROM payment_entries
        WHERE id = %s
          AND is_paid = 0
          AND payment_date IS NULL
    """, (payment.due_id,))

    due = cursor.fetchone()

    if not due:
        cursor.close()
        connection.close()

        return {
            "success": False,
            "message": "Due not found or already paid"
        }

    today = date.today()

    # Keep the transaction number supplied by the Android app. If none was
    # supplied, generate one in the same format used by the existing website.
    transaction_no = payment.transaction_no or ("TXN" + str(secrets.randbelow(9_000_000_000) + 1_000_000_000))
    receipt_no = "BR/{} /{}".format(secrets.randbelow(900) + 100, today.year).replace(" ", "")
    bill_no = f"{payment.due_id:04d}/{today.year}"
    filename = f"receipt_{datetime.now().strftime('%Y%m%d%H%M%S%f')}.pdf"
    receipt_path = RECEIPT_DIR / filename

    # Fetch the same information used by the website receipt template.
    cursor.execute("""
        SELECT
            pe.amount,
            pe.net_amount,
            pe.payment_date,
            pe.payment_mode,
            pe.transaction_no,
            pe.student_id,
            pe.due_date,
            pem.payment_type,
            CONCAT(sm.first_name, ' ', sm.last_name) AS student_name,
            sm.student_id AS student_code,
            scm.class AS class_name,
            sec.section AS section_name,
            sch.school_name,
            sch.address_line_1 AS school_address,
            sch.logo AS school_logo
        FROM payment_entries pe
        LEFT JOIN payment_entry_master pem ON pe.entry_id = pem.id
        LEFT JOIN student_master sm ON pe.student_id = sm.id
        LEFT JOIN class_master scm ON sm.class_id = scm.id
        LEFT JOIN section_master sec ON sm.section_id = sec.id
        LEFT JOIN school_master sch ON sm.school_id = sch.id
        WHERE pe.id = %s
        LIMIT 1
    """, (payment.due_id,))
    payment_details = cursor.fetchone() or {}

    cursor.execute("""
        UPDATE payment_entries
        SET
            payment_date = %s,
            payment_confirm_date = %s,
            payment_recieve_date = %s,
            payment_mode = %s,
            transaction_no = %s,
            remarks = %s,
            is_paid = 1,
            bill_no = %s,
            receipt_no = %s,
            receipt_date = %s,
            receipt = %s,
            updated_ts = CURRENT_TIMESTAMP
        WHERE id = %s
    """, (
        today,
        today,
        today,
        payment.payment_mode,
        transaction_no,
        payment.remarks,
        bill_no,
        receipt_no,
        today,
        f"{BACKEND_BASE_URL}/receipts/{filename}",
        payment.due_id
    ))

    connection.commit()

    # The existing ClassAI payment transaction above remains authoritative.
    # After it succeeds, trigger the unchanged parent website's own receipt
    # generation for this same payment record. This is best-effort only, so
    # receipt generation can never make Collect Payment fail.
    try:
        form_data = urlencode({
            "payment_id": str(payment.due_id),
            "payment_date": today.isoformat(),
            "payment_mode": (payment.payment_mode or "").strip().upper(),
            "remarks": payment.remarks or "",
        }).encode("utf-8")

        receipt_request = Request(
            "https://classai.fixmyneed.in/submit-payment",
            data=form_data,
            method="POST",
            headers={
                "Content-Type": "application/x-www-form-urlencoded",
                "User-Agent": "ClassAI-Backend/1.0",
                "Origin": "https://classai.fixmyneed.in",
                "Referer": "https://classai.fixmyneed.in/offline-payment",
            },
        )

        class _NoRedirect(HTTPRedirectHandler):
            def redirect_request(self, req, fp, code, msg, headers, newurl):
                return None

        try:
            with build_opener(_NoRedirect).open(receipt_request, timeout=20) as response:
                website_status = response.status
        except HTTPError as exc:
            website_status = exc.code

        if not (200 <= website_status < 400):
            print(f"Website receipt generation returned HTTP {website_status} for payment {payment.due_id}")
    except (URLError, TimeoutError, OSError) as exc:
        print(f"Website receipt generation failed for payment {payment.due_id}: {exc}")

    # Generate the A4 receipt on the backend. The Bluetooth formatter is
    # completely separate and is intentionally not touched.
    _build_receipt_pdf(
        receipt_path=receipt_path,
        school_name=payment_details.get("school_name") or "",
        school_address=payment_details.get("school_address") or "",
        student_name=payment_details.get("student_name") or "",
        student_code=payment_details.get("student_code") or "",
        payment_type=payment_details.get("payment_type") or "",
        transaction_no=transaction_no,
        transaction_date=today.strftime("%d-%m-%Y"),
        payment_mode=payment.payment_mode,
        receipt_no=receipt_no,
        amount=float(due["net_amount"]),
        class_name=payment_details.get("class_name") or "",
        section_name=payment_details.get("section_name") or "",
        month=(payment_details.get("due_date") or today).strftime("%B-%Y") if hasattr((payment_details.get("due_date") or today), "strftime") else ""
    )

    cursor.close()
    connection.close()

    return {
        "success": True,
        "message": "Payment recorded successfully",
        "due_id": payment.due_id,
        "student_id": due["student_id"],
        "transaction_no": transaction_no,
        "amount": due["amount"],
        "penalty": due["penalty"],
        "waiver": due["waiver"],
        "net_amount": due["net_amount"],
        "payment_date": str(today),
        "payment_mode": payment.payment_mode,
        "receipt_no": receipt_no,
        "receipt": f"{BACKEND_BASE_URL}/receipts/{filename}"
    }


@app.get("/receipts/{filename}")
def get_receipt(filename: str):
    # Only serve generated PDF files from the dedicated receipt directory.
    safe_name = os.path.basename(filename)
    if safe_name != filename or not safe_name.lower().endswith(".pdf"):
        raise HTTPException(status_code=404, detail="Receipt not found")

    path = RECEIPT_DIR / safe_name
    if not path.is_file():
        raise HTTPException(status_code=404, detail="Receipt not found")

    return FileResponse(path, media_type="application/pdf", filename=safe_name)


def _build_receipt_pdf(
    receipt_path: Path,
    school_name: str,
    school_address: str,
    student_name: str,
    student_code: str,
    payment_type: str,
    transaction_no: str,
    transaction_date: str,
    payment_mode: str,
    receipt_no: str,
    amount: float,
    class_name: str,
    section_name: str,
    month: str,
):
    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "ReceiptTitle", parent=styles["Title"], fontName="Helvetica-Bold",
        fontSize=17, leading=20, alignment=TA_CENTER, spaceAfter=4
    )
    center = ParagraphStyle(
        "ReceiptCenter", parent=styles["Normal"], fontSize=10,
        leading=13, alignment=TA_CENTER
    )
    body = ParagraphStyle(
        "ReceiptBody", parent=styles["Normal"], fontSize=10,
        leading=14, alignment=TA_LEFT
    )

    doc = SimpleDocTemplate(
        str(receipt_path), pagesize=A4,
        rightMargin=22 * mm, leftMargin=22 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm
    )

    amount_text = f"Rs. {amount:,.2f} /-"
    story = [
        Paragraph(school_name, title),
        Paragraph(school_address, center) if school_address else Spacer(1, 6),
        Spacer(1, 12),
        Paragraph("RECEIPT", title),
        Spacer(1, 8),
    ]

    details = [
        [Paragraph(f"<b>RECEIPT NO.</b> {receipt_no}", body), Paragraph(f"<b>TRANSACTION NO.</b> {transaction_no}", body)],
        [Paragraph(f"<b>TRANSACTION MODE.</b> {payment_mode}", body), Paragraph(f"<b>TRANSACTION DATE.</b> {transaction_date}", body)],
    ]
    table = Table(details, colWidths=[82 * mm, 82 * mm])
    table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)
    story.append(Spacer(1, 12))

    class_section = f" ({class_name}{(' - ' + section_name) if section_name else ''})" if class_name else ""
    story.append(Paragraph(
        f"Received with thanks for <b>{student_name}</b> - {student_code} for {payment_type or 'Fees'} for {month}{class_section}.",
        body
    ))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"Rupees {amount:,.2f} Only.", center))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<b>{amount_text}</b>", center))
    story.append(Spacer(1, 42))
    story.append(Paragraph("This is a computer generated receipt. No signature required.", center))
    story.append(Spacer(1, 18))
    story.append(Paragraph("Powered by Eduplex Solutions Pvt. Ltd.", center))

    doc.build(story)


@app.get("/")
def root():
    return {
        "message": "ClassAI backend is running"
    }


@app.get("/test-db")
def test_database():

    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("SELECT 1")
    result = cursor.fetchone()

    cursor.close()
    connection.close()

    return {
        "database": "connected",
        "result": result[0]
    }


@app.get("/students")
def get_students():

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    cursor.execute("""
        SELECT
            id,
            student_id AS studentId,
            CONCAT(first_name, ' ', last_name) AS name,
            class_id AS classId,
            section_id AS sectionId
        FROM student_master
        WHERE school_id = 3
          AND is_active = 1
    """)

    students = cursor.fetchall()

    cursor.close()
    connection.close()

    return students


@app.get("/classes")
def get_classes():

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    cursor.execute("""
        SELECT
            id,
            class AS name
        FROM class_master
        WHERE school_id = 3
          AND is_active = 1
        ORDER BY id
    """)

    classes = cursor.fetchall()

    cursor.close()
    connection.close()

    return classes


@app.get("/sections")
def get_sections():

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    cursor.execute("""
        SELECT
            id,
            class_id AS classId,
            section AS name
        FROM section_master
        WHERE school_id = 3
          AND is_active = 1
        ORDER BY class_id, id
    """)

    sections = cursor.fetchall()

    cursor.close()
    connection.close()

    return sections


@app.get("/dues/{student_id}")
def get_student_dues(student_id: int):

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    cursor.execute("""
        SELECT
            id,
            student_id AS studentId,
            DATE_FORMAT(due_date, '%M-%Y') AS month,
            DATE_FORMAT(due_date, '%Y-%m-%d') AS dueDate,
            amount AS payableAmount,
            COALESCE(penalty, 0) AS penalty,
            COALESCE(waiver, 0) AS waiver,
            net_amount AS netAmount
        FROM payment_entries
        WHERE student_id = %s
          AND payment_date IS NULL
        ORDER BY due_date
    """, (student_id,))

    dues = cursor.fetchall()

    cursor.close()
    connection.close()

    return dues


# ---------------------------------------------------------------------------
# School / Employee management
# ---------------------------------------------------------------------------

@app.get("/schools")
def get_schools():

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        cursor.execute("""
            SELECT
                id,
                school_name AS schoolName,
                is_active AS isActive
            FROM school_master
            ORDER BY school_name, id
        """)

        return cursor.fetchall()

    finally:
        cursor.close()
        connection.close()


@app.post("/employees")
def create_employee(employee: EmployeeCreate):

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        cursor.execute("""
            SELECT
                id,
                is_active
            FROM school_master
            WHERE id = %s
        """, (employee.schoolId,))

        school = cursor.fetchone()

        if not school:
            return {
                "success": False,
                "message": "School not found"
            }

        if int(school["is_active"]) != 1:
            return {
                "success": False,
                "message": "Selected school is inactive"
            }

        # User ID must be unique across both employee and admin accounts.
        cursor.execute("""
            SELECT user_id
            FROM user_admin
            WHERE user_id = %s

            UNION ALL

            SELECT user_id
            FROM user_accountant
            WHERE user_id = %s

            LIMIT 1
        """, (employee.userId, employee.userId))

        existing_user = cursor.fetchone()

        if existing_user:
            return {
                "success": False,
                "message": "User ID already exists"
            }

        salt = secrets.token_bytes(16)

        password_hash = hashlib.pbkdf2_hmac(
            "sha256",
            employee.password.encode("utf-8"),
            salt,
            100000
        )

        stored_password = (
            "pbkdf2_sha256$100000$"
            + salt.hex()
            + "$"
            + password_hash.hex()
        )

        cursor.execute("""
            INSERT INTO user_accountant (
                school_id,
                full_name,
                mobile,
                user_id,
                password,
                is_active,
                created_ts
            )
            VALUES (
                %s,
                %s,
                %s,
                %s,
                %s,
                1,
                CURRENT_TIMESTAMP
            )
        """, (
            employee.schoolId,
            employee.fullName,
            employee.mobile,
            employee.userId,
            stored_password
        ))

        connection.commit()

        return {
            "success": True,
            "message": "Employee created successfully",
            "employeeId": cursor.lastrowid
        }

    except Exception as e:
        connection.rollback()

        return {
            "success": False,
            "message": str(e)
        }

    finally:
        cursor.close()
        connection.close()


@app.get("/employees")
def get_employees():

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        cursor.execute("""
            SELECT
                ua.id,
                ua.full_name AS fullName,
                ua.mobile,
                ua.user_id AS userId,
                ua.school_id AS schoolId,
                sm.school_name AS schoolName,
                ua.is_active AS isActive
            FROM user_accountant ua
            LEFT JOIN school_master sm
                ON sm.id = ua.school_id
            ORDER BY ua.full_name, ua.id
        """)

        return cursor.fetchall()

    finally:
        cursor.close()
        connection.close()


@app.patch("/employees/{employee_id}")
def update_employee(
    employee_id: int,
    employee: EmployeeUpdate
):
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        cursor.execute("""
            SELECT id, user_id, is_active
            FROM user_accountant
            WHERE id = %s
            LIMIT 1
        """, (employee_id,))

        existing_employee = cursor.fetchone()

        if not existing_employee:
            return {
                "success": False,
                "message": "Employee not found"
            }

        cursor.execute("""
            SELECT id, is_active
            FROM school_master
            WHERE id = %s
            LIMIT 1
        """, (employee.schoolId,))

        school = cursor.fetchone()

        if not school:
            return {
                "success": False,
                "message": "School not found"
            }

        if int(school["is_active"]) != 1:
            return {
                "success": False,
                "message": "Selected school is inactive"
            }

        # User ID uniqueness is global across admins and employees, excluding
        # the employee currently being edited.
        cursor.execute("""
            SELECT user_id
            FROM user_admin
            WHERE user_id = %s

            UNION ALL

            SELECT user_id
            FROM user_accountant
            WHERE user_id = %s
              AND id <> %s

            LIMIT 1
        """, (employee.userId, employee.userId, employee_id))

        existing_user = cursor.fetchone()

        if existing_user:
            return {
                "success": False,
                "message": "User ID already exists"
            }

        if employee.password and employee.password.strip():
            salt = secrets.token_bytes(16)
            password_hash = hashlib.pbkdf2_hmac(
                "sha256",
                employee.password.encode("utf-8"),
                salt,
                100000
            )
            stored_password = (
                "pbkdf2_sha256$100000$"
                + salt.hex()
                + "$"
                + password_hash.hex()
            )

            cursor.execute("""
                UPDATE user_accountant
                SET school_id = %s,
                    full_name = %s,
                    mobile = %s,
                    user_id = %s,
                    password = %s
                WHERE id = %s
            """, (
                employee.schoolId,
                employee.fullName,
                employee.mobile,
                employee.userId,
                stored_password,
                employee_id
            ))
        else:
            cursor.execute("""
                UPDATE user_accountant
                SET school_id = %s,
                    full_name = %s,
                    mobile = %s,
                    user_id = %s
                WHERE id = %s
            """, (
                employee.schoolId,
                employee.fullName,
                employee.mobile,
                employee.userId,
                employee_id
            ))

        connection.commit()

        return {
            "success": True,
            "message": "Employee updated successfully"
        }

    except Exception as e:
        connection.rollback()
        return {
            "success": False,
            "message": str(e)
        }
    finally:
        cursor.close()
        connection.close()


@app.patch("/employees/{employee_id}/status")
def update_employee_status(
    employee_id: int,
    request: AdminStatusUpdate
):
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        cursor.execute("""
            SELECT
                ua.id,
                ua.is_active,
                sm.is_active AS school_is_active
            FROM user_accountant ua
            LEFT JOIN school_master sm
                ON sm.id = ua.school_id
            WHERE ua.id = %s
            LIMIT 1
        """, (employee_id,))

        employee = cursor.fetchone()

        if not employee:
            return {
                "success": False,
                "message": "Employee not found"
            }

        new_status = 1 if int(request.isActive) == 1 else 0

        if new_status == 1 and (
            employee["school_is_active"] is None
            or int(employee["school_is_active"]) != 1
        ):
            return {
                "success": False,
                "message": "Employee cannot be activated while the school is inactive"
            }

        cursor.execute("""
            UPDATE user_accountant
            SET is_active = %s
            WHERE id = %s
        """, (new_status, employee_id))

        connection.commit()

        return {
            "success": True,
            "message": "Employee status updated successfully",
            "isActive": new_status
        }

    except Exception as e:
        connection.rollback()
        return {
            "success": False,
            "message": str(e)
        }
    finally:
        cursor.close()
        connection.close()


@app.patch("/schools/{school_id}/status")
def update_school_status(
    school_id: int,
    request: AdminStatusUpdate
):
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        cursor.execute("""
            SELECT id, is_active
            FROM school_master
            WHERE id = %s
            LIMIT 1
        """, (school_id,))

        school = cursor.fetchone()

        if not school:
            return {
                "success": False,
                "message": "School not found"
            }

        new_status = 1 if int(request.isActive) == 1 else 0

        cursor.execute("""
            UPDATE school_master
            SET is_active = %s
            WHERE id = %s
        """, (new_status, school_id))

        # School status controls all employees belonging to that school.
        # Deactivation disables every employee; reactivation restores them.
        cursor.execute("""
            UPDATE user_accountant
            SET is_active = %s
            WHERE school_id = %s
        """, (new_status, school_id))

        connection.commit()

        return {
            "success": True,
            "message": "School status updated successfully",
            "isActive": new_status
        }

    except Exception as e:
        connection.rollback()
        return {
            "success": False,
            "message": str(e)
        }
    finally:
        cursor.close()
        connection.close()



# ---------------------------------------------------------------------------
# Admin management
# ---------------------------------------------------------------------------

@app.post("/admins")
def create_admin(admin: AdminCreate):

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        # testadmin is permanently reserved for the SuperAdmin.
        if admin.userId.strip() == "testadmin":
            return {
                "success": False,
                "message": "This User ID is reserved for the SuperAdmin"
            }

        # User ID must be unique across both admin and employee accounts.
        cursor.execute("""
            SELECT user_id
            FROM user_admin
            WHERE user_id = %s

            UNION ALL

            SELECT user_id
            FROM user_accountant
            WHERE user_id = %s

            LIMIT 1
        """, (admin.userId, admin.userId))

        existing_user = cursor.fetchone()

        if existing_user:
            return {
                "success": False,
                "message": "User ID already exists"
            }

        salt = secrets.token_bytes(16)

        password_hash = hashlib.pbkdf2_hmac(
            "sha256",
            admin.password.encode("utf-8"),
            salt,
            100000
        )

        stored_password = (
            "pbkdf2_sha256$100000$"
            + salt.hex()
            + "$"
            + password_hash.hex()
        )

        cursor.execute("""
            INSERT INTO user_admin (
                full_name,
                mobile,
                user_id,
                password,
                is_active,
                created_ts
            )
            VALUES (
                %s,
                %s,
                %s,
                %s,
                1,
                CURRENT_TIMESTAMP
            )
        """, (
            admin.fullName,
            admin.mobile,
            admin.userId,
            stored_password
        ))

        connection.commit()

        return {
            "success": True,
            "message": "Admin created successfully",
            "adminId": cursor.lastrowid
        }

    except Exception as e:
        connection.rollback()

        return {
            "success": False,
            "message": str(e)
        }

    finally:
        cursor.close()
        connection.close()


@app.get("/admins")
def get_admins():

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        # testadmin is the protected SuperAdmin and must never
        # appear in the Administrators directory.
        cursor.execute("""
            SELECT
                id,
                full_name AS fullName,
                mobile,
                user_id AS userId,
                is_active AS isActive
            FROM user_admin
            WHERE user_id <> 'testadmin'
            ORDER BY full_name, id
        """)

        return cursor.fetchall()

    finally:
        cursor.close()
        connection.close()


@app.patch("/admins/{admin_id}")
def update_admin_status(
    admin_id: int,
    request: AdminStatusUpdate
):

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        cursor.execute("""
            SELECT
                id,
                user_id
            FROM user_admin
            WHERE id = %s
            LIMIT 1
        """, (admin_id,))

        admin = cursor.fetchone()

        if not admin:
            return {
                "success": False,
                "message": "Admin not found"
            }

        # SuperAdmin can never be modified.
        if admin["user_id"] == "testadmin":
            return {
                "success": False,
                "message": "SuperAdmin cannot be modified"
            }

        new_status = 1 if int(request.isActive) == 1 else 0

        cursor.execute("""
            UPDATE user_admin
            SET is_active = %s
            WHERE id = %s
        """, (
            new_status,
            admin_id
        ))

        connection.commit()

        return {
            "success": True,
            "message": "Admin status updated successfully",
            "isActive": new_status
        }

    except Exception as e:
        connection.rollback()

        return {
            "success": False,
            "message": str(e)
        }

    finally:
        cursor.close()
        connection.close()


@app.get("/profile")
def get_profile(user_id: str, role: str):
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:
        if role == "admin":
            cursor.execute("""
                SELECT
                    ua.full_name AS fullName,
                    ua.user_id AS userId,
                    ua.mobile,
                    ua.is_active AS isActive
                FROM user_admin ua
                WHERE ua.user_id = %s
                LIMIT 1
            """, (user_id,))

            user = cursor.fetchone()

            if not user:
                return {
                    "success": False,
                    "message": "Profile not found"
                }

            user["role"] = "Administrator"
            user["schoolName"] = ""
            return {
                "success": True,
                **user
            }

        if role == "employee":
            cursor.execute("""
                SELECT
                    ua.full_name AS fullName,
                    ua.user_id AS userId,
                    ua.mobile,
                    ua.is_active AS isActive,
                    sm.school_name AS schoolName,
                    sm.is_active AS schoolIsActive
                FROM user_accountant ua
                LEFT JOIN school_master sm
                    ON sm.id = ua.school_id
                WHERE ua.user_id = %s
                LIMIT 1
            """, (user_id,))

            user = cursor.fetchone()

            if not user:
                return {
                    "success": False,
                    "message": "Profile not found"
                }

            user["role"] = "Employee"
            return {
                "success": True,
                **user
            }

        return {
            "success": False,
            "message": "Invalid profile role"
        }

    finally:
        cursor.close()
        connection.close()


# ---------------------------------------------------------------------------
# Login
# ---------------------------------------------------------------------------

@app.post("/login")
def login(request: LoginRequest):

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    try:

        if request.role == "admin":

            cursor.execute("""
                SELECT
                    id,
                    full_name,
                    user_id,
                    password,
                    is_active
                FROM user_admin
                WHERE user_id = %s
                LIMIT 1
            """, (request.userId,))

        elif request.role == "employee":

            cursor.execute("""
                SELECT
                    ua.id,
                    ua.full_name,
                    ua.user_id,
                    ua.password,
                    ua.is_active,
                    sm.is_active AS school_is_active
                FROM user_accountant ua
                LEFT JOIN school_master sm
                    ON sm.id = ua.school_id
                WHERE ua.user_id = %s
                LIMIT 1
            """, (request.userId,))

        else:

            return {
                "success": False,
                "message": "Invalid login role"
            }

        user = cursor.fetchone()

        if not user:

            return {
                "success": False,
                "message": "Invalid User ID or password"
            }

        if int(user["is_active"]) != 1:

            return {
                "success": False,
                "message": "Account is inactive"
            }

        if request.role == "employee":

            if user["school_is_active"] is None:

                return {
                    "success": False,
                    "message": "Employee school not found"
                }

            if int(user["school_is_active"]) != 1:

                return {
                    "success": False,
                    "message": "School is inactive"
                }

        stored_password = user["password"]

        try:

            algorithm, iterations, salt_hex, stored_hash_hex = (
                stored_password.split("$")
            )

            if algorithm != "pbkdf2_sha256":

                return {
                    "success": False,
                    "message": "Invalid account credentials"
                }

            iterations = int(iterations)

            salt = bytes.fromhex(salt_hex)

            calculated_hash = hashlib.pbkdf2_hmac(
                "sha256",
                request.password.encode("utf-8"),
                salt,
                iterations
            )

            if calculated_hash.hex() != stored_hash_hex:

                return {
                    "success": False,
                    "message": "Invalid User ID or password"
                }

        except Exception:

            return {
                "success": False,
                "message": "Invalid account credentials"
            }

        return {
            "success": True,
            "message": "Login successful",
            "userId": user["user_id"],
            "role": request.role,
            "fullName": user["full_name"]
        }

    finally:
        cursor.close()
        connection.close()